package com.github.lunatrius.ingameinfo.integration.terrafirmacraft;

import com.github.lunatrius.ingameinfo.integration.terrafirmacraft.tag.TagTerraFirmaCraft;
import com.github.lunatrius.ingameinfo.reference.Names;
import com.github.lunatrius.ingameinfo.reference.Reference;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.relauncher.Side;

// NOTE: requires VM arguments: -Dfml.coreMods.load=com.bioxx.tfc.TFCASMLoadingPlugin
@Mod(modid = TerraFirmaCraft.MODID, name = TerraFirmaCraft.NAME, version = Reference.VERSION, dependencies = TerraFirmaCraft.DEPENDENCIES)
public class TerraFirmaCraft {
    public static final String MODID = Reference.MODID + "|" + Names.Mods.TERRAFIRMACRAFT_MODID + "Integration";
    public static final String NAME = Reference.NAME + " - " + Names.Mods.TERRAFIRMACRAFT_NAME + " Integration";
    public static final String DEPENDENCIES = "after:" + Reference.MODID + ";after:" + Names.Mods.TERRAFIRMACRAFT_MODID;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        final ModMetadata metadata = event.getModMetadata();
        metadata.autogenerated = false;
        metadata.description = "Compiled against " + Names.Mods.TERRAFIRMACRAFT_MODID + " " + com.bioxx.tfc.Reference.ModVersion;
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        if (FMLCommonHandler.instance().getEffectiveSide() != Side.CLIENT) {
            return;
        }

        if (Loader.isModLoaded(Names.Mods.TERRAFIRMACRAFT_MODID)) {
            TagTerraFirmaCraft.register();
        }
    }
}
