package com.github.lunatrius.ingameinfo.integration.thaumcraft;

import com.github.lunatrius.ingameinfo.integration.thaumcraft.tag.TagThaumcraft;
import com.github.lunatrius.ingameinfo.reference.Names;
import com.github.lunatrius.ingameinfo.reference.Reference;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.relauncher.Side;

@Mod(modid = Thaumcraft.MODID, name = Thaumcraft.NAME, version = Reference.VERSION, dependencies = Thaumcraft.DEPENDENCIES)
public class Thaumcraft {
    public static final String MODID = Reference.MODID + "|" + Names.Mods.THAUMCRAFT_MODID + "Integration";
    public static final String NAME = Reference.NAME + " - " + Names.Mods.THAUMCRAFT_NAME + " Integration";
    public static final String DEPENDENCIES = "after:" + Reference.MODID + ";after:" + Names.Mods.THAUMCRAFT_MODID;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        final ModMetadata metadata = event.getModMetadata();
        metadata.autogenerated = false;
        metadata.description = "Compiled against " + Names.Mods.THAUMCRAFT_MODID + " " + thaumcraft.common.Thaumcraft.VERSION;
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        if (FMLCommonHandler.instance().getEffectiveSide() != Side.CLIENT) {
            return;
        }

        if (Loader.isModLoaded(Names.Mods.THAUMCRAFT_MODID)) {
            TagThaumcraft.register();
        }
    }
}
